In [10]:
import yfinance as yf


# 指定股票代號。
# TSM 是台積電在美股市場的 ADR ticker。
ticker = "TSM"


# 從 yfinance 下載最近 1 個月的每日行情資料。
# tickers=ticker：指定要抓哪一支股票。
# period="1mo"：抓最近 1 個月。
# interval="1d"：每日一筆資料。
# auto_adjust=False：保留 Close 與 Adj Close，方便我們分別存進資料庫。
df = yf.download(
    tickers=ticker,
    period="1mo",
    interval="1d",
    # auto_adjust=False,
)


# 先印出原始欄位，觀察 yfinance 回傳格式。
# 你目前看到的是 MultiIndex：
# ('Open', 'TSM')
# ('High', 'TSM')
# ...

[*********************100%***********************]  1 of 1 completed

In [11]:
# 先印出原始欄位，觀察 yfinance 回傳格式。
# 你目前看到的是 MultiIndex：
# ('Open', 'TSM')
# ('High', 'TSM')
# ...
print("=== 原始欄位 ===")
print(df.columns)

print("=== 原始資料 ===")
print(df.head())

=== 原始欄位 ===
MultiIndex([( 'Close', 'TSM'),
            (  'High', 'TSM'),
            (   'Low', 'TSM'),
            (  'Open', 'TSM'),
            ('Volume', 'TSM')],
           names=['Price', 'Ticker'])
=== 原始資料 ===
Price            Close        High         Low        Open    Volume
Ticker             TSM         TSM         TSM         TSM       TSM
Date
2026-04-23  382.660004  388.760010  375.809998  384.250000  12224900
2026-04-24  402.459991  409.489990  393.850006  396.140015  21603600
2026-04-27  404.980011  414.500000  400.399994  413.750000  16561200
2026-04-28  392.339996  397.869995  384.700012  392.119995  14715800
2026-04-29  393.829987  395.850006  388.179993  392.910004  10313000

In [ ]:
if df.columns.nlevels > 1:
    df.columns = df.columns.droplevel(1)
print("=== drop level ===")
print(df.head())
# df['ticker'] = ticker

=== drop level ===
Price            Close        High         Low        Open    Volume
Date
2026-04-23  382.660004  388.760010  375.809998  384.250000  12224900
2026-04-24  402.459991  409.489990  393.850006  396.140015  21603600
2026-04-27  404.980011  414.500000  400.399994  413.750000  16561200
2026-04-28  392.339996  397.869995  384.700012  392.119995  14715800
2026-04-29  393.829987  395.850006  388.179993  392.910004  10313000

In [ ]:
df['ticker'] = ticker
df.index.name = 'trade_date'
df = df.reset_index()
print("=== reset_index ===")
print(df.head())

=== reset_index ===
Price trade_date       Close        High         Low        Open    Volume
0     2026-04-23  382.660004  388.760010  375.809998  384.250000  12224900
1     2026-04-24  402.459991  409.489990  393.850006  396.140015  21603600
2     2026-04-27  404.980011  414.500000  400.399994  413.750000  16561200
3     2026-04-28  392.339996  397.869995  384.700012  392.119995  14715800
4     2026-04-29  393.829987  395.850006  388.179993  392.910004  10313000

In [16]:
# 新增ticker
df['ticker'] = ticker
df.head()

Price,trade_date,Close,High,Low,Open,Volume,ticker
0,2026-04-23,382.660004,388.760010,375.809998,384.250000,12224900,TSM
1,2026-04-24,402.459991,409.489990,393.850006,396.140015,21603600,TSM
2,2026-04-27,404.980011,414.500000,400.399994,413.750000,16561200,TSM
3,2026-04-28,392.339996,397.869995,384.700012,392.119995,14715800,TSM
4,2026-04-29,393.829987,395.850006,388.179993,392.910004,10313000,TSM

In [17]:
df.columns.name = None
df.head()

  trade_date       Close        High         Low        Open    Volume ticker
0 2026-04-23  382.660004  388.760010  375.809998  384.250000  12224900    TSM
1 2026-04-24  402.459991  409.489990  393.850006  396.140015  21603600    TSM
2 2026-04-27  404.980011  414.500000  400.399994  413.750000  16561200    TSM
3 2026-04-28  392.339996  397.869995  384.700012  392.119995  14715800    TSM
4 2026-04-29  393.829987  395.850006  388.179993  392.910004  10313000    TSM

In [ ]:
df